name: samba-py
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - nibabel
  - nilearn
  - scikit-image
  - matplotlib
  - pyyaml
  - tqdm
  - pytest
  - black
  - ruff
